site_name: Belajar Data Science
repo_url: https://github.com/RISTEK-Data-Science-Analytics/belajardatsci
theme:
  name: material
  language: en
  logo: assets/ristek-logo-light.png
  favicon: assets/ristek-logo-dark.png
  palette:
    primary: custom
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link 
    - content.code.annotation
    - content.code.copy
    - navigation.expand

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/RISTEK-Data-Science-Analytics
  generator: false

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - tags

nav:
  - Home: 'index.md'
  - Fundamental:
    - Pengenalan: './fundamentals/introduction.md'
    - Task: './fundamentals/task.md'
    - Metrics: './fundamentals/metrics.md'
  - Tabular:
    - Pengenalan: './tabular/introduction.md'
    - 'Pembersihan Data': './tabular/data-cleaning.md'
    - 'Rekayasa Fitur': './tabular/feature-engineering.md'
    - Crossvalidation: './tabular/crossvalidation.md'
    - Pipeline: './tabular/pipeline.md'


copyright:
  Copyright &copy; 2023 <a href="https://github.com/RISTEK-Data-Science-Analytics" target="_blank" rel="noopener">Ristek Data Science and Analytics</a>